#!/bin/bash

#to update Bobs current ip address for remote access
IP=`dig +short myip.opendns.com @resolver1.opendns.com`
file=/home/badmin/current_ip

date >> $file
echo $IP >> $file

rsync -e 'ssh -p 22' $file ladmin@tom.bn1.io:/home/ladmin/

exit 0
